<a href="https://colab.research.google.com/github/frsantiagojr/LinearAlgebra_2021_2021/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Linear Algebra for ECE

### Laboratory 6: Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vector as well as the fundamental of matrices, we'll try to the same oerations with matrices and even more.

### Objectives

At the end of this ativity you will be able to:

1.   Be familiar with the fundamental matix operations.
2.   Apply the operations to solve intermediate equations.
3.   Apply matrix algebra in engineering solutions.





### Discussion

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$A^T = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

This can now be achieved programmatically by using np.transpose() or using the T method.

In [ ]:
A = np.array([[1, 2, 5],
             [5, -1, 0],
             [0, -3, 3]])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
              [1,2,3,4],
              [1,0,2,1]
              ])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

In [ ]:
C = np.array([
              [2, 3, 8],
              [8, 5, 6]
])
C

array([[2, 3, 8],
       [8, 5, 6]])

In [ ]:
C.shape

(2, 3)

In [ ]:
np.transpose(C)

array([[2, 8],
       [3, 5],
       [8, 6]])

In [ ]:
C.T.shape

(3, 2)

### Dot Product

Dot Product / Inner Product
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&amp;x_{(0,1)}\\ x_{(1,0)}&amp;x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&amp;y_{(0,1)}\\ y_{(1,0)}&amp;y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} &amp; x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} &amp; x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:$$X = \begin{bmatrix}1&amp;2\\ 0&amp;1\end{bmatrix}, Y = \begin{bmatrix}-1&amp;0\\ 2&amp;2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 &amp; 1*0 + 2*2 \\  0*-1 + 1*2 &amp; 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 &amp; 4 \\2 &amp; 2 \end{bmatrix}$$

This could be achieved programmatically using np.dot(), np.matmul() or the @ operator.

In [ ]:
X = np.array([
              [1, 2],
              [0, 1]
])
Y = np.array([
              [-1, 0],
              [2, 2]
              ])
np.dot(X, Y)

In [ ]:
np.dot(X, Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X @ Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X, Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
F = np.array([
              [9, 9, 8],
              [1, 1, 2]
])
R = np.array([
             [1, 5],
             [2, 4],
             [6, 9]
])

In [ ]:
np.dot(F, R)

array([[ 75, 153],
       [ 15,  27]])

In [ ]:
F.dot(R)

array([[ 75, 153],
       [ 15,  27]])

In [ ]:
F @ R

array([[ 75, 153],
       [ 15,  27]])

In [ ]:
np.matmul(F, R)

array([[ 75, 153],
       [ 15,  27]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

##**Rule 1: The inner dimensions of the two matrices in question must be the same**

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&amp;4\\5&amp;-2\\0&amp;1\end{bmatrix}, B = \begin{bmatrix}1&amp;1\\3&amp;3\\-1&amp;-2\end{bmatrix}, C = \begin{bmatrix}0&amp;1&amp;1\\1&amp;1&amp;2\end{bmatrix}$$
So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.

In [ ]:
A = np.array([
              [2, 4],
              [5, -2],
              [0, 1]
])
B = np.array([
              [1, 1],
              [3, 3],
              [1, 2]
])
C = np.array([
              [0, 1, 1],
              [1, 1, 2]
])



In [ ]:
A.shape
B.shape
C.shape


(2, 3)

In [ ]:
A @ C


array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [ ]:
B @ C

array([[1, 2, 3],
       [3, 6, 9],
       [2, 3, 5]])

In [ ]:
A @ B


ValueError: ignored

In [ ]:
A @ B.T

array([[ 6, 18, 10],
       [ 3,  9,  1],
       [ 1,  3,  2]])

In [ ]:
X = np.array([
              [1,2,3,0]
])
Y = np.array([
              [1, 0, 4, -1]
])

In [ ]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [ ]:
X @ Y.T

array([[13]])

##**Rule 2: Dot Product has special properties**


Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:

$A \cdot B \neq B \cdot A$

$A \cdot (B \cdot C) = (A \cdot B) \cdot C$

$A\cdot(B+C) = A\cdot B + A\cdot C$

$(B+C)\cdot A = B\cdot A + C\cdot A$

$A\cdot I = A$

$A\cdot \emptyset = \emptyset$

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [ ]:
J = np.array([
              [1, 1, -2],
              [5, 6, 8],
              [2, 3, 5]

])
R = np.array([
              [6, 7, 9], 
              [5, 8, -1],
              [-2, 7, 6]
])
S = np.array([
              [1, 2, 9],
              [9, 8, 7],
              [6, 5, 4]
])


In [ ]:
F1 = J @ R
F2 = R @ J

In [ ]:
np.array_equal(F1, F2)

False

In [ ]:
F3 = J @ (R @ S)
F4 = (J @ R) @ S

In [ ]:
np.array_equal(F3, F4)

True

In [ ]:
F5 = J @ (R + S) 
F6 = (J @ R) + (J @ S)

In [ ]:
np.array_equal(F5, F6)

True

In [ ]:
F7 = (R + S) @ J
F8 = (R @ J) + (S @ J)

In [ ]:
np.array_equal(F7, F8)

True

In [ ]:
F9 = J @ np.eye(3)


In [ ]:
np.array_equal(F9, J)

True

### Determinants

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:$$A = \begin{bmatrix}a_{(0,0)}&amp;a_{(0,1)}\\a_{(1,0)}&amp;a_{(1,1)}\end{bmatrix}$$We can compute for the determinant as:$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$So if we have $A$ as:$$A = \begin{bmatrix}1&amp;4\\0&amp;3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using np.linalg.det().

In [ ]:
A = np.array([
              [1, 4],
              [0, 3]
])

In [ ]:
np.linalg.det(A)

3.0000000000000004

In [ ]:
B = np.array([
              [1, 5, 2],
              [3, -1, -1],
              [0, -2, 1]
])

In [ ]:
np.linalg.det(B)

-30.000000000000014

### Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:$$M = \begin{bmatrix}1&amp;7\\-3&amp;5\end{bmatrix}$$First, we need to get the determinant of $M$.$$|M| = (1)(5)-(-3)(7) = 26$$Next, we need to reform the matrix into the inverse form:$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} &amp; -m_{(0,1)} \\ -m_{(1,0)} &amp; m_{(0,0)}\end{bmatrix}$$So that will be:$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 &amp; -7 \\ 3 &amp; 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} &amp; \frac{-7}{26} \\ \frac{3}{26} &amp; \frac{1}{26}\end{bmatrix}$$For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use np.linalg.inv().

In [ ]:
K = np.array([
              [1, -5, 7],
              [6, 4, 8],
              [9, 7, -2]
])

L = np.linalg.inv(K)

In [ ]:
K @ L

array([[ 1.00000000e+00, -8.32667268e-17, -5.55111512e-17],
       [ 4.16333634e-17,  1.00000000e+00, -2.22044605e-16],
       [-1.76941795e-16, -2.77555756e-17,  1.00000000e+00]])

In [ ]:
M = K @ L

In [ ]:
np.array(M, dtype=int)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]])

#**Activity**


##**Task 1**

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [3]:
F = np.array([
          [1, -5, 9],
          [-7, 2, 8],
          [4, 3, -6]
          ])
R = np.array([
              [5, -2, 3],
              [4, 8, 2],
              [-1, 1, 9]
])
S = np.array([
              [2, 4, -7],
              [1, 4, 1],
              [4, 3, 8]
])
I = np.eye(3)
J = np.zeros(3)







### Commutative Property

Matrix Multiplication is not commutative. This is because multipliying matrix not just element by element which has different product if applying commutative property. As an example, using the Matrix Above the product of F x R not equal to R x F. Numpy **array_equal()** function can be use to verify if the two matrices are equal. 

In [ ]:
A1 = F @ R

In [ ]:
A2 = R @ F

In [ ]:
A1

array([[-24, -33,  74],
       [-35,  38,  55],
       [ 38,  10, -36]])

In [ ]:
A2

array([[ 31, -20,  11],
       [-44,   2,  88],
       [ 28,  34, -55]])

In [ ]:
np.array_equal(A1, A2)


False

### ASSOCIATIVE PROPERTY

You can change the grouping of the matrices and the product are still equal.

In [4]:
A3 = (F @ R) @ S
A4 = F @ (R @ S)

np.array_equal(A3, A4)

True

### DISTRIBUTIVE PROPERTY

The Matrices can be distributed just like in real numbers

In [5]:
A5 = F @ (R + S)
A6 = (F @ R) + (F @ S)
np.array_equal(A5, A6)

True

###IDENTITY PROPERTY

Multiplying an n x n matrix to an identity matrix is equal to the n x n matrix.

In [6]:
A7 = F @ I
np.array_equal(A7, F)

True

### ZERO PROPERTY

Any n x n matrix multiply by n x n zero matrix is equal to zero.

In [8]:
A8 = R @ J
np.array_equal(A8, J)

True

# CONCLUSION

I conclude that with this laboratory excercise, I had been able to familiarize myself in matrix operations. I learned how to do transposition, dot products and determinants. Also, I am able to execute matrix multipilcation properties using numpy. 